import { Router } from 'express';
import authRoutes from './auth';
import productRoutes from './products';
import cartRoutes from './cart';
import orderRoutes from './orders';
import userRoutes from './users';
import vendorRoutes from './vendors';
import categoryRoutes from './categories';
import dropshippingRoutes from './dropshipping';
import analyticsRoutes from './analytics';
import crmRoutes from './crm';
import financialRoutes from './financial';
import fulfillmentRoutes from './fulfillment';
import hrRoutes from './hr';
import inventoryRoutes from './inventory';
import productionRoutes from './production';
import purchaseOrderRoutes from './purchaseOrders';
import qualityRoutes from './quality';

const router = Router();

router.use('/auth', authRoutes);
router.use('/products', productRoutes);
router.use('/cart', cartRoutes);
router.use('/orders', orderRoutes);
router.use('/users', userRoutes);
router.use('/vendors', vendorRoutes);
router.use('/categories', categoryRoutes);
router.use('/dropshipping', dropshippingRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/crm', crmRoutes);
router.use('/financial', financialRoutes);
router.use('/fulfillment', fulfillmentRoutes);
router.use('/hr', hrRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/production', productionRoutes);
router.use('/purchase-orders', purchaseOrderRoutes);
router.use('/quality', qualityRoutes);

export default router;
